### ISSUE TITLE
SolutionsInfini is now Kaleyra

### ISSUE THREAD

**Issue by josejibin** [knadh/otpgateway-solsms#1]
solutionsinfini (https://www.solutionsinfini.com/) changed to kaleyra and there is a new version of API available for sending SMS (https://apidocs-sms.kaleyra.com/?version=latest)

**Comment by knadh** [comment]
Why don't you send a PR?

**Comment by knadh** [comment]
Cheers: https://github.com/knadh/otpgateway-solsms/pull/2.
